//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETL_DaDo_Bier.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Connections : global::System.Configuration.ApplicationSettingsBase {
        
        private static Connections defaultInstance = ((Connections)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Connections())));
        
        public static Connections Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.248;Initial Catalog=DadoBier_Cubo;Persist Security Info=Tru" +
            "e;User ID=dado;Password=Dad01995")]
        public string QueopsCubo {
            get {
                return ((string)(this["QueopsCubo"]));
            }
        }
    }
}
